# Generated by Django 3.2.12 on 2023-07-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('Journal_Title', models.CharField(max_length=100)),
                ('Num_Entries', models.IntegerField()),
                ('Century', models.CharField(max_length=2)),
                ('Journal_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
